using './consolidation-containerapp.module.bicep'

param consolidation_containerimage = '{{ .Image }}'
param consolidation_containerport = '{{ targetPortOrDefault 8080 }}'
param consolidation_identity_outputs_clientid = '{{ .Env.CONSOLIDATION_IDENTITY_CLIENTID }}'
param consolidation_identity_outputs_id = '{{ .Env.CONSOLIDATION_IDENTITY_ID }}'
param env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param env_outputs_azure_container_apps_environment_id = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param env_outputs_azure_container_registry_endpoint = '{{ .Env.ENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param env_outputs_azure_container_registry_managed_identity_id = '{{ .Env.ENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param keyvault_uri = '{{ .Env.KEYVAULT_URI }}'
param secrets_identity_id = '{{ .Env.SECRETS_IDENTITY_ID }}'
param postgres_outputs_connectionstring = '{{ .Env.POSTGRES_CONNECTIONSTRING }}'
param postgres_outputs_hostname = '{{ .Env.POSTGRES_HOSTNAME }}'
