using './transactions-containerapp.module.bicep'

param env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param env_outputs_azure_container_apps_environment_id = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param env_outputs_azure_container_registry_endpoint = '{{ .Env.ENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param env_outputs_azure_container_registry_managed_identity_id = '{{ .Env.ENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param gateway_secret_value = '{{ securedParameter "gateway_secret" }}'
param messaging_password_value = '{{ securedParameter "messaging_password" }}'
param postgres_outputs_connectionstring = '{{ .Env.POSTGRES_CONNECTIONSTRING }}'
param postgres_outputs_hostname = '{{ .Env.POSTGRES_HOSTNAME }}'
param transactions_containerimage = '{{ .Image }}'
param transactions_containerport = '{{ targetPortOrDefault 8080 }}'
param transactions_identity_outputs_clientid = '{{ .Env.TRANSACTIONS_IDENTITY_CLIENTID }}'
param transactions_identity_outputs_id = '{{ .Env.TRANSACTIONS_IDENTITY_ID }}'
